#!/bin/bash

if [ -z "$EDITOR" ]; then
    EDITOR="vi"
else
    EDITOR="$EDITOR"
fi

if [ -z "$1" ]; then
    echo "No config file provided. Type \"$(basename $0) --help\" for usage."
    exit 1
fi

declare -A configs
configs["cfg"]="~/.scripts/cfg"
configs["i3"]="~/.config/i3/config"
configs["alias"]="~/.config/aliasrc"
configs["keys"]="~/.config/sxhkd/sxhkdrc"
configs["mutt"]="~/.mutt/muttrc"
configs["nvim"]="~/.config/nvim/init.vim"
configs["bash"]="~/.bashrc"
configs["p"]="~/.profile"
configs["dunst"]="~/.config/dunst/dunstrc"
configs["st"]="~/.programs/st/config.h"

usage="usage: $(basename $0) [-h] CONFIG -- easily edit common configuration files 

options:
    -h  show this help text

supported configs:"

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    echo "$usage"
    for i in "${!configs[@]}"; do
        echo "     ${i}: ${configs[$i]}"
    done
    exit 0
fi

for i in "${!configs[@]}"; do
    if [ "$i" = "$1" ]; then
        eval temp_path=${configs[$i]}
        "$EDITOR" "$temp_path"
        exit 0
    fi
done
echo "Config file $1 not found. Type \"$(basename $0) --help\" for supported configs."
