#!/usr/bin/env bash

mimetype=$(xclip -o -se c | file --mime-type -b -)
if [[ "$mimetype" == "text/plain" ]]; then
    xclip -o -se c | xargs curl -L | upload
else
    xclip -t image/png -o -se c | upload
fi
