#!/bin/bash

FOLDER="/home/steven/Documents/Sounds/"

FILE=$(ls -1 $FOLDER | grep wav | sed -e 's/\.wav$//' | rofi -dmenu)
if [ -z "$FILE" ]; then exit 0; fi
mpv --audio-device="pulse/SFX" --speed=1 "$FOLDER/$FILE.wav" --volume=75 & disown
sleep 0.15
ID=$(pactl list sink-inputs | grep mpv -m 1 -B16 | head -1 | cut -d "#" -f2 | cut -d " " -f1)
echo $ID
pactl set-sink-input-volume $ID 75%
