#!/bin/bash 
set -e
set -o pipefail

# $1 file name
# $2 short url

# Clear clipboard
echo -n '' | xclip -i -se c

path="-"
if [ ! -z "$1" ]; then
    path="$1"
fi
url=$(curl -s -H 'Accept: application/json' -H 'LinxRandomize: yes' -T "$path" https://fs.ikl.sh/upload/ | jq -r '.["direct_url"]' <&0)
short "$url" "$2" | xclip -i -se c
