#!/bin/sh

# Clear clipboard
echo -n '' | xclip -i -se c

if [ -z "$1" ]; then
    url="$(curl -s -H 'Accept: application/json' -H 'LinxRandomize: yes' -T - https://fs.ikl.sh/upload/ | jq -r '.["direct_url"]' <&0)"
    short "$url" | xclip -i -se c
else
    echo "$1"
    url="$(curl -s -H 'Accept: application/json' -H 'LinxRandomize: yes' -T \"$1\" https://fs.ikl.sh/upload/ | jq -r '.["direct_url"]' <&0)"
    short "$url"
fi

